# Generated by Django 5.1 on 2024-08-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_delete_react'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='Mathematics', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='Sardar', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Shafiq', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='fee',
            field=models.IntegerField(),
        ),
    ]
