# Generated by Django 5.1 on 2024-08-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
